In [ ]:
import numpy as np
import pandas as pd

In [ ]:
data = pd.read_csv("2021_기본조사_20221123_82663.csv",encoding='cp949')
data

,[분석변수(가공)] 장애인고용여부(DIS_T 가공),[분석변수(가공)] 장애인고용률(DIS_T/EMP_T*100),[분석변수(가공)] 업종(A3_1 가공),[분석변수(가공)] 본사소재 지역(A5 가공),[분석변수(가공)] 종사자 규모(B9 가공),[분석변수(가공)] 고용의무기업체 여부(B9 가공),[분석변수(가공)] 부담금납부대상 여부(B9 가공),[분석변수(가공)] 조직형태(A4),[B9. 근로자현황] 전체 근로자 수(전체),[B9. 근로자현황] 전체 근로자 수(남자),...,[B10. 장애인현황] 7 정신(합계),[B10. 장애인현황] 8 자폐성(합계),[B10. 장애인현황] 9 신장(합계),[B10. 장애인현황] 10 심장(합계),[B10. 장애인현황] 11 호흡기(합계),[B10. 장애인현황] 12 간(합계),[B10. 장애인현황] 13 안면(합계),[B10. 장애인현황] 14 장루요루(합계),[B10. 장애인현황] 15 뇌전증(합계),[B10. 장애인현황] 16 유공자(합계)
0,1,0.070621,3,1,5,2,1,2,1416,585,...,0,0,0,0,0,0,0,0,0,0
1,1,0.078740,3,1,5,2,1,3,2540,1701,...,0,0,0,0,0,0,0,0,0,0
2,1,0.105263,3,1,4,2,1,2,950,522,...,0,0,0,0,0,0,0,0,0,0
3,1,0.128899,3,1,5,2,1,3,3879,784,...,0,0,0,0,0,0,0,0,0,0
4,1,0.146628,3,1,4,2,1,2,682,356,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30977,2,0.000000,4,3,3,2,2,2,65,60,...,0,0,0,0,0,0,0,0,0,0
30978,2,0.000000,4,3,3,2,2,2,71,60,...,0,0,0,0,0,0,0,0,0,0
30979,2,0.000000,4,3,3,2,2,2,79,70,...,0,0,0,0,0,0,0,0,0,0
30980,2,0.000000,4,3,3,2,2,3,56,43,...,0,0,0,0,0,0,0,0,0,0
30981,2,0.000000,4,3,3,2,2,3,61,45,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
data.columns = ['장애인고용여부','장애인고용률','업종','본사소재지역','종사자규모','고용의무기업체여부','부담금납부대상여부','조직형태','전체근로자수(전체)','전체근로자수(남자)','전체근로자수(여자)','장애인근로자수(전체)','장애인근로자수(남자)','장애인근로자수(여자)','장애인(합계)','지체','뇌병변','시각','청각','언어','지적','정신','자폐성','신장','심장','호흡기','간','안면','장루요루','뇌전증','유공자']
data

,장애인고용여부,장애인고용률,업종,본사소재지역,종사자규모,고용의무기업체여부,부담금납부대상여부,조직형태,전체근로자수(전체),전체근로자수(남자),...,정신,자폐성,신장,심장,호흡기,간,안면,장루요루,뇌전증,유공자
0,1,0.070621,3,1,5,2,1,2,1416,585,...,0,0,0,0,0,0,0,0,0,0
1,1,0.078740,3,1,5,2,1,3,2540,1701,...,0,0,0,0,0,0,0,0,0,0
2,1,0.105263,3,1,4,2,1,2,950,522,...,0,0,0,0,0,0,0,0,0,0
3,1,0.128899,3,1,5,2,1,3,3879,784,...,0,0,0,0,0,0,0,0,0,0
4,1,0.146628,3,1,4,2,1,2,682,356,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30977,2,0.000000,4,3,3,2,2,2,65,60,...,0,0,0,0,0,0,0,0,0,0
30978,2,0.000000,4,3,3,2,2,2,71,60,...,0,0,0,0,0,0,0,0,0,0
30979,2,0.000000,4,3,3,2,2,2,79,70,...,0,0,0,0,0,0,0,0,0,0
30980,2,0.000000,4,3,3,2,2,3,56,43,...,0,0,0,0,0,0,0,0,0,0
30981,2,0.000000,4,3,3,2,2,3,61,45,...,0,0,0,0,0,0,0,0,0,0

In [5]:
data['장애인고용여부'].replace(1,"장애인 고용기업체",inplace=True)
data['장애인고용여부'].replace(2,"장애인 미고용기업체",inplace=True)

In [8]:
data['업종'].replace({1:"제조업",2:"서비스업1",3:"서비스업2",4:"기타산업"},inplace=True)
data['본사소재지역'].replace({1:"수도권",2:"광역시권",3:"기타지역"},inplace=True)
data['종사자규모'].replace({1:"1~4명",2:"5~49명",3:"50~299명",4:"300~999명",5:"1,000명 이상"},inplace=True)
data['고용의무기업체여부'].replace({1:"고용 비의무",2:"고용 의무"},inplace=True)
data['부담금납부대상여부'].replace({1:"부담금 납부 대상(100명 이상)",2:"부담금 납부 미대상(100명 미만)"},inplace=True)
data['조직형태'].replace({1:"개인기업체",2:"회사법인",3:"회사이외법인"},inplace=True)

In [9]:
data

,장애인고용여부,장애인고용률,업종,본사소재지역,종사자규모,고용의무기업체여부,부담금납부대상여부,조직형태,전체근로자수(전체),전체근로자수(남자),...,정신,자폐성,신장,심장,호흡기,간,안면,장루요루,뇌전증,유공자
0,장애인 고용기업체,0.070621,서비스업2,수도권,"1,000명 이상",고용 의무,부담금 납부 대상(100명 이상),회사법인,1416,585,...,0,0,0,0,0,0,0,0,0,0
1,장애인 고용기업체,0.078740,서비스업2,수도권,"1,000명 이상",고용 의무,부담금 납부 대상(100명 이상),회사이외법인,2540,1701,...,0,0,0,0,0,0,0,0,0,0
2,장애인 고용기업체,0.105263,서비스업2,수도권,300~999명,고용 의무,부담금 납부 대상(100명 이상),회사법인,950,522,...,0,0,0,0,0,0,0,0,0,0
3,장애인 고용기업체,0.128899,서비스업2,수도권,"1,000명 이상",고용 의무,부담금 납부 대상(100명 이상),회사이외법인,3879,784,...,0,0,0,0,0,0,0,0,0,0
4,장애인 고용기업체,0.146628,서비스업2,수도권,300~999명,고용 의무,부담금 납부 대상(100명 이상),회사법인,682,356,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30977,장애인 미고용기업체,0.000000,기타산업,기타지역,50~299명,고용 의무,부담금 납부 미대상(100명 미만),회사법인,65,60,...,0,0,0,0,0,0,0,0,0,0
30978,장애인 미고용기업체,0.000000,기타산업,기타지역,50~299명,고용 의무,부담금 납부 미대상(100명 미만),회사법인,71,60,...,0,0,0,0,0,0,0,0,0,0
30979,장애인 미고용기업체,0.000000,기타산업,기타지역,50~299명,고용 의무,부담금 납부 미대상(100명 미만),회사법인,79,70,...,0,0,0,0,0,0,0,0,0,0
30980,장애인 미고용기업체,0.000000,기타산업,기타지역,50~299명,고용 의무,부담금 납부 미대상(100명 미만),회사이외법인,56,43,...,0,0,0,0,0,0,0,0,0,0
30981,장애인 미고용기업체,0.000000,기타산업,기타지역,50~299명,고용 의무,부담금 납부 미대상(100명 미만),회사이외법인,61,45,...,0,0,0,0,0,0,0,0,0,0

In [10]:
data.to_csv("기업체장애인고용실태조사.csv")